"use client"
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { useRouter,usePathname } from "next/navigation";
import { useEffect } from "react";
import { isLoggedIn } from "@/utils/auth.js";
import '@fortawesome/fontawesome-free/css/all.min.css';
import {Provider} from "react-redux"
import {store} from "@/redux/store"
import { Loader } from "@/components/loader/Loader";
import {
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter()
  const pathName = usePathname()
  useEffect(() => {
    const isUserValid=async()=>{
      let allowed = ['/signup']
       if(!await isLoggedIn()){
        if(!allowed.includes(pathName)){
          router.push("/login")
        }
      }
    }
    isUserValid()
  }, []);
  const queryClient = new QueryClient()
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <Provider store={store}>
            <Loader/>
            {children}
          </Provider>
        </QueryClientProvider>
        <Toaster />
      </body>
    </html>
  );
}
